function mustBeRemoteGuidanceSimulation(simulation)
% mustBeRemoteGuidanceSimulation 校验远程导引数值仿真结果结构体。
%
% 要求结果包含 wait、transfer、mission、reference、events、impulses 和 validation
% 等块，且时间向量、二维轨迹矩阵与关键事件量尺寸一致。

best_schema = { ...
    'td', utils.schema.doubleScalar('nonnegative')};

wait_schema = { ...
    'time', utils.schema.timeVector(); ...
    'chaser_pos', utils.schema.matrix2xN('time'); ...
    'chaser_vel', utils.schema.matrix2xN('time'); ...
    'target_pos', utils.schema.matrix2xN('time'); ...
    'target_vel', utils.schema.matrix2xN('time'); ...
    'capture_pos', utils.schema.matrix2xN('time'); ...
    'capture_vel', utils.schema.matrix2xN('time')};

transfer_schema = { ...
    'time', utils.schema.timeVector(); ...
    'time_abs', utils.schema.timeVector('time'); ...
    'chaser_pos', utils.schema.matrix2xN('time'); ...
    'chaser_vel', utils.schema.matrix2xN('time'); ...
    'target_pos', utils.schema.matrix2xN('time'); ...
    'target_vel', utils.schema.matrix2xN('time'); ...
    'capture_pos', utils.schema.matrix2xN('time'); ...
    'capture_vel', utils.schema.matrix2xN('time')};

mission_schema = { ...
    'time', utils.schema.timeVector(); ...
    'chaser_pos', utils.schema.matrix2xN('time'); ...
    'target_pos', utils.schema.matrix2xN('time'); ...
    'capture_pos', utils.schema.matrix2xN('time')};

reference_schema = { ...
    'target_time', utils.schema.timeVector(); ...
    'target_pos', utils.schema.matrix2xN('target_time'); ...
    'target_vel', utils.schema.matrix2xN('target_time'); ...
    'chaser_time', utils.schema.timeVector(); ...
    'chaser_pos', utils.schema.matrix2xN('chaser_time'); ...
    'chaser_vel', utils.schema.matrix2xN('chaser_time')};

events_schema = { ...
    'start', utils.schema.vector2x1(); ...
    'departure', utils.schema.vector2x1(); ...
    'arrival_capture', utils.schema.vector2x1(); ...
    'arrival_target', utils.schema.vector2x1()};

impulses_schema = { ...
    'dv1_vec', utils.schema.vector2x1(); ...
    'dv2_vec_design', utils.schema.vector2x1(); ...
    'dv2_vec_numeric', utils.schema.vector2x1()};

validation_schema = { ...
    'departure_position_error', utils.schema.doubleScalar('nonnegative'); ...
    'departure_velocity_error', utils.schema.doubleScalar('nonnegative'); ...
    'arrival_position_error', utils.schema.doubleScalar('nonnegative'); ...
    'arrival_velocity_error', utils.schema.doubleScalar('nonnegative'); ...
    'capture_velocity_error', utils.schema.doubleScalar('nonnegative'); ...
    'dv2_numeric_vec', utils.schema.vector2x1(); ...
    'dv2_numeric', utils.schema.doubleScalar('nonnegative'); ...
    'dv2_vector_error', utils.schema.doubleScalar('nonnegative')};

schema = { ...
    'mu', utils.schema.doubleScalar('positive'); ...
    'Re', utils.schema.doubleScalar('positive'); ...
    'best', utils.schema.nested(best_schema); ...
    'wait', utils.schema.nested(wait_schema); ...
    'transfer', utils.schema.nested(transfer_schema); ...
    'mission', utils.schema.nested(mission_schema); ...
    'reference', utils.schema.nested(reference_schema); ...
    'events', utils.schema.nested(events_schema); ...
    'impulses', utils.schema.nested(impulses_schema); ...
    'validation', utils.schema.nested(validation_schema); ...
    'axis_limit_km', utils.schema.doubleScalar('positive')};

utils.schema.validateStruct(simulation, schema, 'simulation');

end
