function [Phi_rr, Phi_rv, Phi_vr, Phi_vv] = cw_stm(n, t)

nt = n * t;
s = sin(nt);
c = cos(nt);

Phi_rr = [4 - 3 * c, 0, 0; ...
              6 * (s - nt), 1, 0; ...
              0, 0, c];

Phi_rv = [s / n, 2 * (1 - c) / n, 0; ...
              2 * (c - 1) / n, (4 * s - 3 * nt) / n, 0; ...
              0, 0, s / n];

Phi_vr = [3 * n * s, 0, 0; ...
              6 * n * (c - 1), 0, 0; ...
              0, 0, -n * s];

Phi_vv = [c, 2 * s, 0; ...
              -2 * s, 4 * c - 3, 0; ...
              0, 0, c];

end
