function simulation = simulate_impulsive_proximity_guidance_2d( ...
    mu, Re, target, initial_relative, plan, config)
% simulate_impulsive_proximity_guidance_2d 在惯性系中用 ode113 校核近距离导引设计。
%
% 输入：
%   mu                地球引力参数。
%   Re                地球半径。
%   target            目标圆轨道参数结构体。
%   initial_relative  初始相对状态结构体，包含 rel_r0 与 rel_v0。
%   plan              多脉冲设计结果结构体。
%   config            数值校核配置结构体，包含段内积分步长与切入后
%                     绕飞保持验证时长。
%
% 输出：
%   simulation        数值校核结果结构体，主要包含：
%                     1. segments：各脉冲段的惯性系与 LVLH 系历史；
%                     2. transfer_*：转移段数值与解析轨迹；
%                     3. mission / relative：包含切入后绕飞段的全程轨迹；
%                     4. events / final：各节点事件状态与末端插入状态；
%                     5. post_insert：切入后无控绕飞保持验证历史；
%                     6. validation：解析解与数值积分解的误差统计。
%
% 说明：
%   本函数把每次脉冲视为瞬时速度增量。段内先在惯性系中分别推进目标
%   与跟踪器的两体运动，再逐点回到 LVLH 系，与同一段对应的 CW
%   解析解进行对比；末端切入脉冲施加后，再继续做一段无控传播，
%   检查是否保持在目标绕飞轨道附近。

arguments
    mu (1,1) double {mustBePositive}
    Re (1,1) double {mustBePositive}
    target (1,1) struct
    initial_relative (1,1) struct
    plan (1,1) struct
    config (1,1) struct {mustBeProximitySimulationConfig} = struct( ...
        'segment_step', 10, ...
        'post_insert_duration', 0, ...
        'post_insert_step', 10)
end

[target_pos_0, target_vel_0] = fpkinematics.targetStateCircular2D(target.t0, mu, target);
[chaser_pos_0, chaser_vel_0] = fpkinematics.lvlhToInertial2D( ...
    target_pos_0, target_vel_0, initial_relative.rel_r0, initial_relative.rel_v0);
segments = repmat(struct( ...
    'index', 0, ...
    'time_local', zeros(1, 0), ...
    'time_abs', zeros(1, 0), ...
    'target_pos', zeros(2, 0), ...
    'target_vel', zeros(2, 0), ...
    'chaser_pos', zeros(2, 0), ...
    'chaser_vel', zeros(2, 0), ...
    'rel_r_numeric', zeros(2, 0), ...
    'rel_v_numeric', zeros(2, 0), ...
    'rel_r_analytic', zeros(2, 0), ...
    'rel_v_analytic', zeros(2, 0), ...
    'position_error', zeros(1, 0), ...
    'velocity_error', zeros(1, 0), ...
    'dv_inertial', zeros(2, 1)), 1, plan.N);
mission_blocks = repmat(createEmptyMissionBlock(), 1, plan.N);

node_time = plan.time_nodes;
node_target_pos = zeros(2, plan.N + 1);
node_target_vel = zeros(2, plan.N + 1);
node_chaser_pos = zeros(2, plan.N + 1);
node_chaser_vel = zeros(2, plan.N + 1);
node_rel_r_numeric = zeros(2, plan.N + 1);
node_rel_v_numeric = zeros(2, plan.N + 1);
node_rel_v_design = zeros(2, plan.N + 1);

node_target_pos(:, 1) = target_pos_0;
node_target_vel(:, 1) = target_vel_0;
node_chaser_pos(:, 1) = chaser_pos_0;
node_chaser_vel(:, 1) = chaser_vel_0;
node_rel_r_numeric(:, 1) = initial_relative.rel_r0;
node_rel_v_numeric(:, 1) = initial_relative.rel_v0;
node_rel_v_design(:, 1) = initial_relative.rel_v0;

current_time = target.t0;
current_target_pos = target_pos_0;
current_target_vel = target_vel_0;
current_chaser_pos = chaser_pos_0;
current_chaser_vel = chaser_vel_0;

for k = 1:plan.N
    frame = fpkinematics.lvlhFrame2D(current_target_pos, current_target_vel);
    dv_inertial = frame.C_L2I * plan.dv_segments(:, k);
    chaser_vel_plus = current_chaser_vel + dv_inertial;

    local_time = fpkinematics.buildTimeGrid(plan.dt_segment, config.segment_step);
    abs_time = current_time + local_time;

    [target_pos_hist, target_vel_hist] = fpkinematics.propagateTwoBodyOde1132D( ...
        current_target_pos, current_target_vel, local_time, mu);
    [chaser_pos_hist, chaser_vel_hist] = fpkinematics.propagateTwoBodyOde1132D( ...
        current_chaser_pos, chaser_vel_plus, local_time, mu);

    [rel_r_numeric_hist, rel_v_numeric_hist] = fpkinematics.relativeHistoryFromInertial2D( ...
        target_pos_hist, target_vel_hist, chaser_pos_hist, chaser_vel_hist);
    [rel_r_analytic_hist, rel_v_analytic_hist] = cw_history_2d( ...
        target.n, plan.segments(k).rel_r_start, plan.segments(k).rel_v_plus_start, local_time);

    position_error_hist = vecnorm(rel_r_numeric_hist - rel_r_analytic_hist, 2, 1);
    velocity_error_hist = vecnorm(rel_v_numeric_hist - rel_v_analytic_hist, 2, 1);

    segments(k).index = k;
    segments(k).time_local = local_time;
    segments(k).time_abs = abs_time;
    segments(k).target_pos = target_pos_hist;
    segments(k).target_vel = target_vel_hist;
    segments(k).chaser_pos = chaser_pos_hist;
    segments(k).chaser_vel = chaser_vel_hist;
    segments(k).rel_r_numeric = rel_r_numeric_hist;
    segments(k).rel_v_numeric = rel_v_numeric_hist;
    segments(k).rel_r_analytic = rel_r_analytic_hist;
    segments(k).rel_v_analytic = rel_v_analytic_hist;
    segments(k).position_error = position_error_hist;
    segments(k).velocity_error = velocity_error_hist;
    segments(k).dv_inertial = dv_inertial;

    if k == 1
        idx_use = 1:numel(local_time);
    else
        idx_use = 2:numel(local_time);
    end

    mission_blocks(k) = createMissionBlock( ...
        abs_time(idx_use), ...
        target_pos_hist(:, idx_use), ...
        target_vel_hist(:, idx_use), ...
        chaser_pos_hist(:, idx_use), ...
        chaser_vel_hist(:, idx_use), ...
        rel_r_numeric_hist(:, idx_use), ...
        rel_v_numeric_hist(:, idx_use), ...
        rel_r_analytic_hist(:, idx_use), ...
        rel_v_analytic_hist(:, idx_use));

    current_time = abs_time(end);
    current_target_pos = target_pos_hist(:, end);
    current_target_vel = target_vel_hist(:, end);
    current_chaser_pos = chaser_pos_hist(:, end);
    current_chaser_vel = chaser_vel_hist(:, end);

    node_target_pos(:, k + 1) = current_target_pos;
    node_target_vel(:, k + 1) = current_target_vel;
    node_chaser_pos(:, k + 1) = current_chaser_pos;
    node_chaser_vel(:, k + 1) = current_chaser_vel;
    node_rel_r_numeric(:, k + 1) = rel_r_numeric_hist(:, end);
    node_rel_v_numeric(:, k + 1) = rel_v_numeric_hist(:, end);
    node_rel_v_design(:, k + 1) = plan.segments(k).rel_v_end_minus;
end

transfer_history = mergeMissionBlocks(mission_blocks);
mission_time = transfer_history.time;
mission_target_pos = transfer_history.target_pos;
mission_target_vel = transfer_history.target_vel;
mission_chaser_pos = transfer_history.chaser_pos;
mission_chaser_vel = transfer_history.chaser_vel;
mission_rel_r_numeric = transfer_history.rel_r_numeric;
mission_rel_v_numeric = transfer_history.rel_v_numeric;
mission_rel_r_analytic = transfer_history.rel_r_analytic;
mission_rel_v_analytic = transfer_history.rel_v_analytic;

frame_final = fpkinematics.lvlhFrame2D(current_target_pos, current_target_vel);
dv_terminal_inertial = frame_final.C_L2I * plan.dv_terminal;
chaser_vel_inserted = current_chaser_vel + dv_terminal_inertial;

[rel_r_arrival_numeric, rel_v_arrival_numeric] = fpkinematics.inertialToLvlh2D( ...
    current_target_pos, current_target_vel, current_chaser_pos, current_chaser_vel);
[rel_r_inserted_numeric, rel_v_inserted_numeric] = fpkinematics.inertialToLvlh2D( ...
    current_target_pos, current_target_vel, current_chaser_pos, chaser_vel_inserted);

post_insert_time = fpkinematics.buildTimeGrid(config.post_insert_duration, config.post_insert_step);
post_insert_time_abs = current_time + post_insert_time;
[post_target_pos, post_target_vel] = fpkinematics.propagateTwoBodyOde1132D( ...
    current_target_pos, current_target_vel, post_insert_time, mu);
[post_chaser_pos, post_chaser_vel] = fpkinematics.propagateTwoBodyOde1132D( ...
    current_chaser_pos, chaser_vel_inserted, post_insert_time, mu);
[post_rel_r_numeric, post_rel_v_numeric] = fpkinematics.relativeHistoryFromInertial2D( ...
    post_target_pos, post_target_vel, post_chaser_pos, post_chaser_vel);
post_insert_theta = plan.theta + target.n * post_insert_time;
[post_rel_r_reference, post_rel_v_reference] = proximity_reference_orbit_state_2d( ...
    target.n, plan.orbit, post_insert_theta);
post_position_error = vecnorm(post_rel_r_numeric - post_rel_r_reference, 2, 1);
post_velocity_error = vecnorm(post_rel_v_numeric - post_rel_v_reference, 2, 1);

transfer_position_error = vecnorm(mission_rel_r_numeric - mission_rel_r_analytic, 2, 1);
transfer_velocity_error = vecnorm(mission_rel_v_numeric - mission_rel_v_analytic, 2, 1);

mission_time_full = [mission_time, post_insert_time_abs];
mission_target_pos_full = [mission_target_pos, post_target_pos];
mission_target_vel_full = [mission_target_vel, post_target_vel];
mission_chaser_pos_full = [mission_chaser_pos, post_chaser_pos];
mission_chaser_vel_full = [mission_chaser_vel, post_chaser_vel];
mission_rel_r_numeric_full = [mission_rel_r_numeric, post_rel_r_numeric];
mission_rel_v_numeric_full = [mission_rel_v_numeric, post_rel_v_numeric];
mission_rel_r_reference_full = [mission_rel_r_analytic, post_rel_r_reference];
mission_rel_v_reference_full = [mission_rel_v_analytic, post_rel_v_reference];

validation = struct();
validation.transfer_max_position_error = max(transfer_position_error);
validation.transfer_max_velocity_error = max(transfer_velocity_error);
validation.arrival_position_error = norm(rel_r_arrival_numeric - plan.rel_rf);
validation.arrival_velocity_error = norm(rel_v_arrival_numeric - plan.rel_vf_minus);
validation.node_position_error = vecnorm(node_rel_r_numeric - plan.rel_r_seq, 2, 1);
validation.node_velocity_error = vecnorm(node_rel_v_numeric - node_rel_v_design, 2, 1);
validation.post_insert_max_position_error = max(post_position_error);
validation.post_insert_max_velocity_error = max(post_velocity_error);

simulation = struct();
simulation.mu = mu;
simulation.Re = Re;
simulation.target = target;
simulation.initial_relative = initial_relative;
simulation.plan = plan;
simulation.segments = segments;
simulation.mission = struct( ...
    'time', mission_time_full, ...
    'target_pos', mission_target_pos_full, ...
    'target_vel', mission_target_vel_full, ...
    'chaser_pos', mission_chaser_pos_full, ...
    'chaser_vel', mission_chaser_vel_full);
simulation.transfer_mission = struct( ...
    'time', mission_time, ...
    'target_pos', mission_target_pos, ...
    'target_vel', mission_target_vel, ...
    'chaser_pos', mission_chaser_pos, ...
    'chaser_vel', mission_chaser_vel);
simulation.relative = struct( ...
    'time', mission_time_full, ...
    'numeric_r', mission_rel_r_numeric_full, ...
    'numeric_v', mission_rel_v_numeric_full, ...
    'analytic_r', mission_rel_r_reference_full, ...
    'analytic_v', mission_rel_v_reference_full);
simulation.transfer_relative = struct( ...
    'time', mission_time, ...
    'numeric_r', mission_rel_r_numeric, ...
    'numeric_v', mission_rel_v_numeric, ...
    'analytic_r', mission_rel_r_analytic, ...
    'analytic_v', mission_rel_v_analytic);
simulation.post_insert = struct( ...
    'time', post_insert_time, ...
    'time_abs', post_insert_time_abs, ...
    'theta', post_insert_theta, ...
    'target_pos', post_target_pos, ...
    'target_vel', post_target_vel, ...
    'chaser_pos', post_chaser_pos, ...
    'chaser_vel', post_chaser_vel, ...
    'rel_r_numeric', post_rel_r_numeric, ...
    'rel_v_numeric', post_rel_v_numeric, ...
    'rel_r_reference', post_rel_r_reference, ...
    'rel_v_reference', post_rel_v_reference, ...
    'position_error', post_position_error, ...
    'velocity_error', post_velocity_error);
simulation.events = struct( ...
    'node_time', node_time, ...
    'target_pos', node_target_pos, ...
    'target_vel', node_target_vel, ...
    'chaser_pos', node_chaser_pos, ...
    'chaser_vel', node_chaser_vel, ...
    'inserted_chaser_vel', chaser_vel_inserted);
simulation.final = struct( ...
    'target_pos', current_target_pos, ...
    'target_vel', current_target_vel, ...
    'rel_r_arrival_numeric', rel_r_arrival_numeric, ...
    'rel_v_arrival_numeric', rel_v_arrival_numeric, ...
    'rel_r_inserted_numeric', rel_r_inserted_numeric, ...
    'rel_v_inserted_numeric', rel_v_inserted_numeric, ...
    'dv_terminal_inertial', dv_terminal_inertial);
simulation.validation = validation;

end

function mustBeProximitySimulationConfig(config)
% mustBeProximitySimulationConfig 校验数值仿真配置。

schema = { ...
    'segment_step', utils.schema.doubleScalar('positive'); ...
    'post_insert_duration', utils.schema.doubleScalar('nonnegative'); ...
    'post_insert_step', utils.schema.doubleScalar('positive')};

utils.schema.validateStruct(config, schema, 'config');

end

function block = createEmptyMissionBlock()
% createEmptyMissionBlock 创建单段任务历史块的空模板。

block = createMissionBlock( ...
    zeros(1, 0), ...
    zeros(2, 0), ...
    zeros(2, 0), ...
    zeros(2, 0), ...
    zeros(2, 0), ...
    zeros(2, 0), ...
    zeros(2, 0), ...
    zeros(2, 0), ...
    zeros(2, 0));

end

function block = createMissionBlock( ...
    time, target_pos, target_vel, chaser_pos, chaser_vel, ...
    rel_r_numeric, rel_v_numeric, rel_r_analytic, rel_v_analytic)
% createMissionBlock 收集单段转移历史，便于后续统一拼接。

block = struct( ...
    'time', time, ...
    'target_pos', target_pos, ...
    'target_vel', target_vel, ...
    'chaser_pos', chaser_pos, ...
    'chaser_vel', chaser_vel, ...
    'rel_r_numeric', rel_r_numeric, ...
    'rel_v_numeric', rel_v_numeric, ...
    'rel_r_analytic', rel_r_analytic, ...
    'rel_v_analytic', rel_v_analytic);

end

function merged = mergeMissionBlocks(blocks)
% mergeMissionBlocks 将各段任务历史块拼接为连续时程。

merged = struct( ...
    'time', [blocks.time], ...
    'target_pos', cat(2, blocks.target_pos), ...
    'target_vel', cat(2, blocks.target_vel), ...
    'chaser_pos', cat(2, blocks.chaser_pos), ...
    'chaser_vel', cat(2, blocks.chaser_vel), ...
    'rel_r_numeric', cat(2, blocks.rel_r_numeric), ...
    'rel_v_numeric', cat(2, blocks.rel_v_numeric), ...
    'rel_r_analytic', cat(2, blocks.rel_r_analytic), ...
    'rel_v_analytic', cat(2, blocks.rel_v_analytic));

end

function [rel_r_history, rel_v_history] = cw_history_2d(n, rel_r_start, rel_v_plus_start, time_list)
% cw_history_2d 用 CW 状态转移矩阵生成单段内的解析相对状态历史。

sample_num = numel(time_list);
rel_r_history = zeros(2, sample_num);
rel_v_history = zeros(2, sample_num);

for i = 1:sample_num
    tau = time_list(i);
    [Phi_rr, Phi_rv, Phi_vr, Phi_vv] = cw_stm_2d(n, tau);

    rel_r_history(:, i) = Phi_rr * rel_r_start + Phi_rv * rel_v_plus_start;
    rel_v_history(:, i) = Phi_vr * rel_r_start + Phi_vv * rel_v_plus_start;
end

end
